[package]
name = "space-invaders"
version = "0.1.0"
edition = "2021"
include = [ "resources/**/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
mint = "0.5.9"
rand = "0.8.5"
